# Generated by Django 5.1 on 2024-10-18 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('client_first_name', models.CharField(max_length=50)),
                ('client_last_name', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_price', models.FloatField(default=0)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_image', models.CharField(max_length=255)),
                ('product_width', models.FloatField(default=0)),
                ('product_height', models.FloatField(default=0)),
                ('product_thickness', models.FloatField(default=0)),
                ('product_material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_rating', models.FloatField(default=0)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_state', models.CharField(max_length=50)),
                ('supplier_city', models.CharField(max_length=50)),
                ('supplier_zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(choices=[('Supplier', 'Supplier'), ('Client', 'Client')], max_length=20)),
                ('user_auth_provider', models.CharField(choices=[('Internal', 'Internal'), ('Facebook', 'Facebook'), ('iOS', 'Ios')], default='Internal', max_length=20)),
                ('user_auth_provider_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id_address', models.AutoField(primary_key=True, serialize=False)),
                ('client_address', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=50)),
                ('client_state', models.CharField(max_length=50)),
                ('client_zip_code', models.CharField(max_length=10)),
                ('client_address_additional_information', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.clientaddress')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], max_length=20)),
                ('payment_amount', models.FloatField()),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_order_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id_recycle', models.AutoField(primary_key=True, serialize=False)),
                ('recycle_name', models.CharField(max_length=255)),
                ('recycle_image', models.CharField(max_length=255)),
                ('recycle_description', models.CharField(max_length=255)),
                ('recycle_address', models.CharField(max_length=255)),
                ('recycle_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_tracking_number', models.CharField(max_length=50)),
                ('shipment_carrier', models.CharField(max_length=50)),
                ('shipment_status', models.CharField(max_length=50)),
                ('shipment_date', models.DateTimeField()),
                ('shipment_estimated_delivery_date', models.DateTimeField()),
                ('shipment_actual_delivery_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id_cart', models.AutoField(primary_key=True, serialize=False)),
                ('cart_product_quantity', models.IntegerField(default=1)),
                ('cart_added_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierPaymentMethodModel',
            fields=[
                ('id_supplier_payment', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_method_id', models.CharField(max_length=255)),
                ('supplier_payment_method', models.CharField(choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20)),
                ('supplier_payment_email', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSales',
            fields=[
                ('Supplier_order_sales', models.AutoField(primary_key=True, serialize=False)),
                ('total_sales', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.useraccount'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id_reset', models.AutoField(primary_key=True, serialize=False)),
                ('reset_code', models.CharField(max_length=10)),
                ('reset_expiration_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.useraccount'),
        ),
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id_wish', models.AutoField(primary_key=True, serialize=False)),
                ('wish_date_added', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
