# Generated by Django 4.2.3 on 2024-10-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycle',
            name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Client'}, on_delete=django.db.models.deletion.CASCADE, to='product.useraccount', unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_role': 'Supplier'}, on_delete=django.db.models.deletion.CASCADE, to='product.useraccount', unique=True),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmethodmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='product.supplier'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_auth_provider',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Facebook', 'Facebook'), ('iOS', 'iOS')], default='Internal', max_length=20),
        ),
    ]
