# Generated by Django 5.1 on 2024-10-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_recycle_client_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/products_images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='recycle_image',
            field=models.ImageField(upload_to='static/products_images/', verbose_name='Recycle Image'),
        ),
    ]
