# Generated by Django 5.1 on 2024-10-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_supplier_supplier_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_phone_number',
        ),
    ]
