# Generated by Django 4.2.3 on 2024-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_supplier_supplier_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/products_images/', verbose_name='Product Image'),
        ),
    ]
