# Generated by Django 4.2.3 on 2024-11-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_payment_order_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client_address_additional_information',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client_zip_code',
            field=models.IntegerField(),
        ),
    ]
