# Generated by Django 4.2.3 on 2024-11-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
