# Generated by Django 4.2.3 on 2024-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_shipment_shipment_actual_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_codes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
