# Generated by Django 4.2.3 on 2024-11-21 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_payment_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('occurrence_datetime', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('milestone', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='product.shipment')),
            ],
        ),
    ]
