# Generated by Django 4.2.3 on 2024-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_shipment_courier_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status_milestone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
