# Generated by Django 4.2.3 on 2024-11-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_supplierpaymentmethodmodel_supplier_method_id_and_more'),
        ('product', '0012_shipment_status_category_shipment_status_code_and_more'),
    ]

    operations = [
    ]
