# Generated by Django 4.2.3 on 2024-11-22 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_historialcompras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='wish_date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
