# Generated by Django 4.2.3 on 2024-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('cuenta_paypal', models.EmailField(max_length=254)),
            ],
        ),
    ]
